USE [master]
GO
/****** Object:  Database [DapperDemo]    Script Date: 19/09/2019 15:50:36 ******/
CREATE DATABASE [DapperDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DapperSample', FILENAME = N'C:\Users\Antonio Chamorro\DapperSample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DapperSample_log', FILENAME = N'C:\Users\Antonio Chamorro\DapperSample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DapperDemo] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DapperDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DapperDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DapperDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DapperDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DapperDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DapperDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [DapperDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DapperDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DapperDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DapperDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DapperDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DapperDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DapperDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DapperDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DapperDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DapperDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DapperDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DapperDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DapperDemo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DapperDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DapperDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DapperDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DapperDemo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DapperDemo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DapperDemo] SET  MULTI_USER 
GO
ALTER DATABASE [DapperDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DapperDemo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DapperDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DapperDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DapperDemo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DapperDemo] SET QUERY_STORE = OFF
GO
USE [DapperDemo]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [DapperDemo]
GO
/****** Object:  Table [Courses]    Script Date: 19/09/2019 15:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Courses](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](150) NULL,
	[DurationHours] [int] NOT NULL,
	[Price] [money] NOT NULL,
 CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CoursesStudents]    Script Date: 19/09/2019 15:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CoursesStudents](
	[CourseId] [int] NOT NULL,
	[StudentId] [int] NOT NULL,
 CONSTRAINT [PK_CoursesStudents] PRIMARY KEY CLUSTERED 
(
	[CourseId] ASC,
	[StudentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Students]    Script Date: 19/09/2019 15:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Students](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](150) NULL,
 CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Courses]    Script Date: 19/09/2019 15:50:36 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Courses] ON [Courses]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Students]    Script Date: 19/09/2019 15:50:36 ******/
CREATE NONCLUSTERED INDEX [IX_Students] ON [Students]
(
	[FirstName] ASC,
	[LastName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [CoursesStudents]  WITH CHECK ADD  CONSTRAINT [FK_CoursesStudents_Courses] FOREIGN KEY([CourseId])
REFERENCES [Courses] ([ID])
GO
ALTER TABLE [CoursesStudents] CHECK CONSTRAINT [FK_CoursesStudents_Courses]
GO
ALTER TABLE [CoursesStudents]  WITH CHECK ADD  CONSTRAINT [FK_CoursesStudents_Students] FOREIGN KEY([StudentId])
REFERENCES [Students] ([ID])
GO
ALTER TABLE [CoursesStudents] CHECK CONSTRAINT [FK_CoursesStudents_Students]
GO
USE [master]
GO
ALTER DATABASE [DapperDemo] SET  READ_WRITE 
GO
